### ISSUE TITLE
burger not toggling drawer

### ISSUE THREAD

**Issue by aspacardin** [vincurekf/Native-like-Framework#13]
This framework is awesome, it should be the default for ionic! However, the drawer is not toggled by default by the burger. After doing some debugging, the drawer show/hide functions are getting called, but somehow nlDrawer.openned is set too fast. One quick fix i found for this is adding a timeout for nlDrawer.openned= true/false in nlDrawer.show/hide. Is there any other solution?

      setTimeout( function(){
        nlDrawer.openned = false;
      }, $nlConfig.options.speed);

**Comment by vincurekf** [comment]
Hi aspacardin, in browser or on mobile?
I can't reproduce this (haven't came across this issue) but it could be related to device performance.
Have you tried different devices?

Bacause ```nlDrawer.openned``` only tells the ```nlDrawer.toggle()``` function if toggle the drawer on or off (and is called before the ```openned``` value is set by ```hide()``` or ```show()``` function) so this should be working properly.

**Comment by aspacardin** [comment]
I think it was working in browser, but not on mobile. The device i'm using is a Sony Z3, so it's pretty performant. I'm using cordova 5.3, ionic and crosswalk. Actually my final solution was to remove the timeout I mentioned in my previous post, and manually toggle the drawer with an <nlBurger ng-click=drawer.toggle()>. It's working great now. Also, I didn't get the point of the nlDrawer.openned = true; in move(), so I removed that line and I added some event firing when the drawer is open/closed (it might be good to include those custom events as default).

**Comment by vincurekf** [comment]
Yes, the onOpen and onClose events are going to be in next update, with custom callbacks and some other small adjustments. I'm just trying ionic with crosswalk on Nexus 4 and some china Note 3 clone and the drawer works better (drawer toggles every time) on the china model, so that's weird. I'll take a look at that. 
And You are right, there is no need for the nlDrawer.openned = true; in move(), I've probably overlooked that, thank You for mentioning.

**Comment by gabskojima** [comment]
Hello.
I'm using your plugin.
This plugin is wonderful.
However,  I have a small problem about nlDrawer.

My application's nlDrawer has many items, but some items are not appearing on the screen.
I added following code, but it doesn't work properly.

#nlDrawer .nav {
    overflow-y: scroll;
}
I guess the problem is the timing of touch start/end event.

Can you help me?

**Comment by vincurekf** [comment]
gabskojima:

could you try the [full-height](https://github.com/vincurekf/Native-like-Framework/commit/6c04f6334bf051e7f9175b87a59a86382d8152a9) branch? for me it solved the scrolling. 
Sorry for the mess, I had wrong indenting.
Please let me know :)

**Comment by gabskojima** [comment]
vincurekf 

Thank you for your reply.
I tried the full-height branch.
It worked properly.

Thank you!
