### ISSUE TITLE
No Direct integration with existing Framework such as Bootstrap

### ISSUE THREAD

**Issue by siddmegadeth** [vincurekf/Native-like-Framework#21]
No Direct integration with existing Framework such as Bootstrap.
App css parts completely breaks and make the app drawer unable to integrate.

please suggest

**Comment by vincurekf** [comment]
Hi siddmegadeth, that's probably because you are importing bootstrap after nlFrameworks css, could you try to import bootstrap after nlFramework? The styles are minimal, you could also try to debug the styles and check what styles exactly are breaking the app? I am sorry but I can't modify the styles for every other framework out there.

**Comment by siddmegadeth** [comment]
Thanks. I really appreciate your quick response. I really appreciates what you have done because this is something i was looking for a very long time. 
What i am requesting if possible 
Can there be integration with bootstrap so that i can have some form of integration with boostrap and UI.Bootstrap
secondly can there be navbar . suppose i goto to Page1 -> Page2 . is hould be slide right animation and slide left . state can be managed by users. only the animation part for page transition with navbar
this woudl really improve this amazing plugins.

I have tried to load boostrap css after nlFramework.css . I would see if can put these before nlFramework.css

Thanks 
Siddharth
